### PR TITLE
Cleaned `MeanlibRobot` of unused prints and defs

### PR DESCRIPTION
**Pull request by ghost**
## Changes

- Removed printing in `autonomous` to match the other methods.
- Removed `simulationPeriodic` override as it doesn't exist within [`RobotBase`](https://github.com/wpilibsuite/allwpilib/blob/main/wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java#L40).

### CODE REVIEW

**Review by jcrowell — CHANGES_REQUESTED** [review]
We still want the println for autonomous so this shows up in the logs.

**Comment by ghost** [comment]
> We still want the println for autonomous so this shows up in the logs.

Wouldn't `autonomous()` be overridden anyway, or are there times when `autonomous()` is called without being overridden?  If so, shouldn't we consider a more descriptive warning, such as "The autonomous mode was called without being overridden, consider overriding it to enable this mode"?

**Comment by jcrowell** [comment]
There are times where this might not be overridden. It might be nice to add a note to the comment indicating the autonomous was not overwritten but this is not strictly necessary.

**Comment by ghost** [comment]
I've added a message that tells the user that autonomous mode wasn't implemented by them.

**Pull request merged**
